// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjcrqdzflubplaruwnbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqY3JxZHpmbHVicGxhcnV3bmJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4NTg0ODIsImV4cCI6MjA1MzQzNDQ4Mn0.fqh58v701TvMFi9oihZQXZoWBz0zOEjDfw5eCZ-2O2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);